# Generated by Django 2.0.13 on 2019-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_auto_20190421_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200)),
                ('produto_descricao', models.TextField()),
                ('produto_quantidade', models.CharField(max_length=10)),
                ('produto_peso', models.CharField(max_length=10)),
                ('produto_valor', models.CharField(max_length=10)),
                ('produto_valorTotal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VendasRealizadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.CharField(max_length=200)),
            ],
        ),
    ]
