# Generated by Django 2.0.13 on 2019-04-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_venda_vendasrealizadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto_valorTotal',
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto_descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto_peso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto_quantidade',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto_valor',
            field=models.CharField(max_length=200),
        ),
    ]
