# Generated by Django 2.0.13 on 2019-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_auto_20190428_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendasRealizadas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.CharField(max_length=50),
        ),
    ]
