# Generated by Django 2.0.13 on 2019-04-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_auto_20190429_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Produtos',
        ),
    ]
